In [1]:
import JLD
using Colors
import FileIO

In [2]:
folder = "/Users/simon/Data/Sentinel/vejle_2020/factory"
ascending = false
dem_nan = 40;

In [3]:
if ascending 
   # Load
    co_gamma = JLD.load(joinpath(folder,"21VV_coher.jld"),"data")[end:-1:1,:]
    pre_gamma = JLD.load(joinpath(folder,"23VV_coher.jld"),"data")[end:-1:1,:]

    VV_paths = [joinpath(folder,string(i)*"VV_itens.jld") for i=1:3]
    VV = [JLD.load(path,"data")[end:-1:1,:] for path in VV_paths]
    VH_paths = [joinpath(folder,string(i)*"VH_itens.jld") for i=1:3]
    VH = [JLD.load(path,"data")[end:-1:1,:] for path in VH_paths];
    heights = JLD.load(joinpath(folder,"heights.jld"),"data")[end:-1:1,:].-dem_nan;
else
    # Load
    co_gamma = JLD.load(joinpath(folder,"21VV_coher.jld"),"data")[:,end:-1:1]
    pre_gamma = JLD.load(joinpath(folder,"23VV_coher.jld"),"data")[:,end:-1:1]

    VV_paths = [joinpath(folder,string(i)*"VV_itens.jld") for i=1:3]
    VV = [JLD.load(path,"data")[:,end:-1:1] for path in VV_paths]
    VH_paths = [joinpath(folder,string(i)*"VH_itens.jld") for i=1:3]
    VH = [JLD.load(path,"data")[:,end:-1:1] for path in VH_paths];
    heights = JLD.load(joinpath(folder,"heights.jld"),"data")[:,end:-1:1].-dem_nan;
    end;

In [4]:
log_VV = [ 10*log10.(img) for img in VV]

3-element Array{Array{Float64,2},1}:
 [-13.1038 -12.9753 … -14.1872 -12.736; -14.5283 -14.938 … -12.82 -11.9812; … ; -13.4383 -12.9467 … -15.5714 -14.9567; -12.6369 -11.1692 … -14.878 -15.3215]    
 [-12.5332 -8.68533 … -13.0896 -10.8059; -13.7524 -8.39921 … -11.8228 -10.8815; … ; -12.0233 -11.4611 … -18.0358 -18.7519; -10.1811 -8.95163 … -17.908 -18.8796]
 [-14.7107 -15.1116 … -16.4252 -16.1691; -15.7569 -14.5132 … -14.622 -14.5276; … ; -13.1954 -14.2279 … -20.2093 -20.6415; -13.0856 -12.55 … -20.4488 -21.5805]  

In [47]:
function scale_img(img , min , max)
    scale_img = (img.-min)./(max-min)
    scale_img[scale_img.>1] .= 0.999
    scale_img[scale_img.<0] .= 0.001
    return scale_img
end
min_vv = -15
max_vv = 0

0

In [48]:
window = [670:690,840:860];

In [49]:
test =  Colors.Gray.(scale_img(log_VV[1][window...],min_vv,max_vv))
FileIO.save("test_co.jpg",test);
test =  Colors.Gray.(scale_img(log_VV[2][window...],min_vv,max_vv))
FileIO.save("test_pre1.jpg",test);
test =  Colors.Gray.(scale_img(log_VV[3][window...],min_vv,max_vv))
FileIO.save("test_pre2.jpg",test);

img = Colors.RGB{Float32}.(abs.(pre_gamma),abs.(co_gamma),abs.(co_gamma));
FileIO.save("coherence.jpg",img[window...]);

In [46]:
using Statistics

In [34]:
mean(reshape(abs.(pre_gamma[window...]),:))

0.3684827034089397

In [35]:
mean(reshape(abs.(co_gamma[window...]),:))

0.6036907408579755

In [39]:
mu1 = mean(reshape(abs.(VV[1][window...]),:))

0.06475203073731668

In [40]:
mu2 = mean(reshape(abs.(VV[2][window...]),:))

0.09930129417011035

In [42]:
mu3 = mean(reshape(abs.(VV[3][window...]),:))

0.045376357299164616

In [ ]:
(mu1*mu2)/

In [50]:
B = Array{Any}(undef, 2)

2-element Array{Any,1}:
 #undef
 #undef

In [55]:
B .= Missing

2-element Array{Any,1}:
 Missing
 Missing

In [57]:
B[1] == Missing

true

In [59]:
B[1] = VV[1];

In [60]:
B[1] == Missing

false

In [62]:
B

2-element Array{Any,1}:
 [0.0489355 0.0504045 … 0.0381309 0.0532601; 0.0352506 0.0320778 … 0.0522397 0.0633696; … ; 0.0453072 0.0507371 … 0.0277243 0.0319398; 0.0544894 0.0763968 … 0.0325236 0.0293662]
 Missing                                                                                                                                                                         