In [1]:
include("../ToolBox/ToolBox.jl")
using .ToolBox
using .Geometry

In [10]:
test = cat(1:18,2 .*(18:-1:1),dims=1)
test = reshape(test,(6,6))

6×6 Array{Int64,2}:
 1   7  13  36  24  12
 2   8  14  34  22  10
 3   9  15  32  20   8
 4  10  16  30  18   6
 5  11  17  28  16   4
 6  12  18  26  14   2

In [17]:
lines = 1:6
samples = 1:6

1:6

In [49]:
kernel = ones(Int,2,3)

2×3 Array{Int64,2}:
 1  1  1
 1  1  1

In [50]:
res = Misc.fastconv(test,kernel)
res = res[size(kernel)[1]:end-(size(kernel)[1]-1),size(kernel)[2]:end-(size(kernel)[2]-1)]



5×4 Array{Int64,2}:
 45  112  143  138
 51  112  137  126
 57  112  131  114
 63  112  125  102
 69  112  119   90

In [51]:
off_1 = (size(kernel)[1]-1)/2
collect(1-off_1 :1:6+off_1)[size(kernel)[1]:end-(size(kernel)[1]-1)]

5-element Array{Float64,1}:
 1.5
 2.5
 3.5
 4.5
 5.5

In [52]:
off_2 = (size(kernel)[2]-1)/2
collect(1-off_2 :1:6+off_2)[size(kernel)[2]:end-(size(kernel)[2]-1)]

4-element Array{Float64,1}:
 2.0
 3.0
 4.0
 5.0