In [2]:
random = ones(7,7)
random[3, 4] = 5
random

7×7 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  5.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0

In [6]:
kernel = ones(2,3)

2×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [19]:
number_of_rows = size(random)[1] - size(kernel)[1] + 1
number_of_cols = size(random)[2] - size(kernel)[2] + 1
new_arr = Array{Float64, 2}(undef, number_of_rows, number_of_cols)
count = 0
for i in 1:number_of_rows
    for j in 1:number_of_cols
                i_range = i:i + size(kernel)[1] - 1
                j_range = j:j + size(kernel)[2] - 1
                new_arr[i, j] = 1/length(kernel) * sum(kernel .* random[i_range, j_range])
                count += 1
    end
end

In [17]:
new_arr

6×5 Array{Float64,2}:
 1.0  1.0      1.0      1.0      1.0
 1.0  1.66667  1.66667  1.66667  1.0
 1.0  1.66667  1.66667  1.66667  1.0
 1.0  1.0      1.0      1.0      1.0
 1.0  1.0      1.0      1.0      1.0
 1.0  1.0      1.0      1.0      1.0

In [56]:
count

4

In [54]:
size(random)[1] - size(kernel)[1] + 1

4

In [12]:
i_range = 1:1 + size(kernel)[1] - 1
j_range = 1:1 + size(kernel)[2] - 1
random[i_range, j_range]

2×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0

1:2